version: "3.7"

services:
  db:
    image: postgis/postgis:13-3.3
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: consumer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: 
      - "db_data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
  
  app:
    build: .
    container_name: app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_NAME: consumer
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: backend.settings.local
      DEBUG: "False"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: > 
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  test_db:
    image: postgis/postgis:13-3.3
    container_name: postgres_test
    restart: unless-stopped
    environment:
      POSTGRES_DB: consumer_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "7018:5432"

  test:
    build: .
    command: "python manage.py test"
    depends_on:
      - test_db
    environment:
      DB_NAME: consumer_test
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: test_db
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: backend.settings.test
      DEBUG: "False"
    volumes:
      - .:/app

volumes:
  db_data:
