# Generated by Django 5.0.1 on 2024-01-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='previous_job_count',
            new_name='previous_jobs_count',
        ),
    ]
